name: CI

on:
  push:
    branches:
      - pjit_test

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Pip install packages
        run: |
          pip install -e ".[dev,extra]"

      - name: Netket tests
        run: |
          test_sharding/run_test_sharding_distributed.sh
